In [25]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from copy import deepcopy

In [6]:
rawDat = pd.read_excel('MLB-PbP-Sample.xlsx', header = 1)

In [7]:
rawDat.head()

BIGDATABALL\nDATASET          GAME ID       DATE INNING  ROAD\nSCORE  \
0  MLB 2020 Regular Season  44035-SFG@LAD-1 2020-07-23     1T            0   
1  MLB 2020 Regular Season  44035-SFG@LAD-1 2020-07-23     1T            0   
2  MLB 2020 Regular Season  44035-SFG@LAD-1 2020-07-23     1T            0   
3  MLB 2020 Regular Season  44035-SFG@LAD-1 2020-07-23     1T            0   
4  MLB 2020 Regular Season  44035-SFG@LAD-1 2020-07-23     1T            0   

   HOME\nSCORE         BATTING\nTEAM            BATTER  BATTER\nMLB-ID  \
0            0  San Francisco Giants  Mike Yastrzemski          573262   
1            0  San Francisco Giants     Wilmer Flores          527038   
2            0  San Francisco Giants    Pablo Sandoval          467055   
3            0  San Francisco Giants    Alex Dickerson          543105   
4            0  San Francisco Giants      Hunter Pence          452254   

  BATTER\nHAND  ...      HIT TYPE    PLAY TYPE RUNS OUTS STOLEN BASES  \
0            L  ...  GROUND\nBALL  FIELD ERROR  NaN  NaN          NaN   
1            R  ...     FLY\nBALL       FLYOUT  NaN  1.0          NaN   
2            S  ...  GROUND\nBALL       SINGLE  NaN  1.0          NaN   
3            L  ...  GROUND\nBALL       SINGLE  NaN  NaN          NaN   
4            R  ...           NaN    GROUNDOUT  NaN  1.0          NaN   

   CAUGHT STEALING DEFENSIVE INDIFFERENCE PASSED BALL WILD PITCH  \
0              NaN                    NaN         NaN        NaN   
1              NaN                    NaN         NaN        NaN   
2              NaN                    NaN         NaN        NaN   
3              NaN                    NaN         NaN        NaN   
4              NaN                    NaN         NaN        NaN   

                              DESCRIPTION  
0                       Reached on error.  
1          Wilmer Flores flied out to  RF  
2  Single to 3B. Yastrzemski out at 2B/3B  
3            Single to SS. Sandoval to 2B  
4         Hunter Pence grounded out, P-1B  

[5 rows x 44 columns]

In [8]:
rawDat.columns

Index(['BIGDATABALL\nDATASET', 'GAME ID', 'DATE', 'INNING', 'ROAD\nSCORE',
       'HOME\nSCORE', 'BATTING\nTEAM', 'BATTER', 'BATTER\nMLB-ID',
       'BATTER\nHAND', 'RUNNERS ON BASE\n\n1B', 'RUNNERS ON BASE\n\n2B',
       'RUNNERS ON BASE\n\n3B', 'PITCHING\nTEAM', 'PITCHER', 'PITCHER\nMLB-ID',
       'PITCHER\nHAND', 'C', '1B', '2B', '3B', 'SS', 'LF', 'CF', 'RF',
       'PITCHING SEQUENCE LENGTH',
       'PITCH by PITCH\nS: Strike; Strike called; Strike swinging | B: Ball, called ball\nIN: In play | F: Foul; Foul ball on pitchout | FT: Foul tip; Foul tip on bunt | FB: Foul bunt\nIB: Intentional ball | HB: Hit batter | MB: Missed bunt attempt | NP: No pitch\nPO: Pitchout | POS: Swinging on pitchout | N-A: Unknown, Missed pitch | POF Pickoff thrown to 1B/2B/3B',
       'BALLS', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'STRIKES',
       'Unnamed: 32', 'Unnamed: 33', 'HIT TYPE', 'PLAY TYPE', 'RUNS', 'OUTS',
       'STOLEN BASES', 'CAUGHT STEALING', 'DEFENSIVE INDIFFERENCE',
       'PAS

In [5]:
#The ball and strike shit is an annoying format

In [15]:
## we need to drop the useless stuff in the dataframe and reformat the pitch by pitch
## to expand the dataset appropriately 

dropThese = ['BIGDATABALL\nDATASET', 'GAME ID', 'DATE', 'INNING', 'BATTING\nTEAM', 'BATTER', 'BATTER\nMLB-ID',
       'BATTER\nHAND','PITCHING\nTEAM', 'PITCHER', 'PITCHER\nMLB-ID',
       'PITCHER\nHAND', 'C', '1B', '2B', '3B', 'SS', 'LF', 'CF', 'RF', 'PITCHING SEQUENCE LENGTH','HIT TYPE', 'PLAY TYPE','STOLEN BASES', 'CAUGHT STEALING', 'DEFENSIVE INDIFFERENCE',
       'PASSED BALL', 'WILD PITCH', 'DESCRIPTION']

In [26]:
clnDat = rawDat.drop(dropThese, axis = 'columns')
clnDat['PBP'] = deepcopy(clnDat['PITCH by PITCH\nS: Strike; Strike called; Strike swinging | B: Ball, called ball\nIN: In play | F: Foul; Foul ball on pitchout | FT: Foul tip; Foul tip on bunt | FB: Foul bunt\nIB: Intentional ball | HB: Hit batter | MB: Missed bunt attempt | NP: No pitch\nPO: Pitchout | POS: Swinging on pitchout | N-A: Unknown, Missed pitch | POF Pickoff thrown to 1B/2B/3B'])
clnDat = clnDat.drop('PITCH by PITCH\nS: Strike; Strike called; Strike swinging | B: Ball, called ball\nIN: In play | F: Foul; Foul ball on pitchout | FT: Foul tip; Foul tip on bunt | FB: Foul bunt\nIB: Intentional ball | HB: Hit batter | MB: Missed bunt attempt | NP: No pitch\nPO: Pitchout | POS: Swinging on pitchout | N-A: Unknown, Missed pitch | POF Pickoff thrown to 1B/2B/3B' ,axis = 'columns')

In [28]:
## all NaNs are 0 
clnDat = clnDat.fillna(0)
clnDat
## Really we need to drop balls and strikes because we have to infer it from the 'PBP'
## also want to go thru runners on base and replace string with 1 

dropBallStrike = ['BALLS', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'STRIKES',
       'Unnamed: 32', 'Unnamed: 33']
clnDat = clnDat.drop(dropBallStrike, axis = 'columns')

In [29]:
clnDat

ROAD\nSCORE  HOME\nSCORE RUNNERS ON BASE\n\n1B RUNNERS ON BASE\n\n2B  \
0              0            0                     0                     0   
1              0            0      Mike Yastrzemski                     0   
2              0            0      Mike Yastrzemski                     0   
3              0            0        Pablo Sandoval                     0   
4              0            0        Alex Dickerson        Pablo Sandoval   
..           ...          ...                   ...                   ...   
115            4            1      Asdrubal Cabrera                     0   
116            4            1      Asdrubal Cabrera                     0   
117            4            1                     0                     0   
118            4            1                     0                     0   
119            4            1             Luke Voit                     0   

    RUNNERS ON BASE\n\n3B  RUNS  OUTS                        PBP  
0                       0   0.0   0.0      IN                     
1                       0   0.0   1.0    S/S/IN                   
2                       0   0.0   1.0     S/IN                    
3                       0   0.0   0.0   B/B/S/IN                  
4                       0   0.0   1.0     S/IN                    
..                    ...   ...   ...                        ...  
115                     0   0.0   1.0    B/S/S/S                  
116                     0   0.0   1.0   S/S/B/B/S                 
117                     0   0.0   1.0   S/S/F/B/S                 
118                     0   0.0   0.0  F/B/B/B/S/B                
119                     0   0.0   0.0      IN                     

[120 rows x 8 columns]

In [34]:
allvals = [val.split('/') for val in clnDat['PBP'].values]

splts = []

for val in allvals:
    
    for va in val:
        
        splts.append( va.replace(' ', '') )

In [39]:
np.unique(np.array(splts), return_counts = True)

(array(['B', 'F', 'FB', 'FT', 'HB', 'IN', 'S'], dtype='<U2'),
 array([153,  66,   2,   5,   2,  78, 124]))

In [81]:
## I need a way to translate the codes in the PBP to rows of balls and strikes

## Codes and assumptions
    ## IN -- in play so the state moves to the next batter-pitcher with [0,0]
    ## S  -- strike -- easy
    ## B   -- ball --easy
    ## F   -- foul ball on pitchout (what happens?)
    ## FT  -- foul tip on bunt (what happens?)
    ## FB  -- foul bunt (so what? )
    ## HB  -- hit batter (I guess this just resets the strike ball states)
    ## IB  -- intentional ball (this is just a ball I think)
    ## MB  -- misses bunt attempt (isn't that a strike?)
    ## NP  -- no pitch (what?)
    ## PO  -- what
    ## POS -- swinging on pitchout (?)
    ## N-A -- unknown missed pitch damn
    
    ## the unique entries in this dataset are

def pbpToBallStrikeArray(pbp):
    ## the array is just going to be a pitchX2 array with each row being [#strike, #ball]
    sequence = pbp.split('/')
    
    arr = np.zeros(shape = (len(sequence), 2))
    
    balls   = 0
    strikes = 0
    
    for i, seq in enumerate(sequence):
        if seq in ['IN', 'HB']:
            
            break # new batter
        
        if seq in ['B'] :
            
            balls += 1
            arr[i + 1] = np.array([balls, strikes])
            
        if seq in ['S'] :
            
            strikes += 1
            arr[i + 1] = np.array([balls, strikes])
            
        if seq in ['F','FB','FT'] :
            ## foul -- either nothing happens or you 
            ## get a strike if strike < 2
            
            arr[i + 1] = np.array([balls, strikes])
            
            if strikes < 2:
                strikes += 1
                
            
    return arr


In [82]:
## lets test on some of the pbp

In [89]:
idx = 30

In [90]:
clnDat['PBP'].iloc[idx]

'B/F/IN                 '

In [91]:
pbpToBallStrikeArray(clnDat['PBP'].iloc[idx])

array([[0., 0.],
       [1., 0.],
       [1., 0.]])

In [92]:
## ok now to expand the dataframe appropriately. 

## pretty much you just repeat the same row with the sequential strike and ball data


In [99]:
cols = ['RUNNERS ON BASE\n\n1B','RUNNERS ON BASE\n\n2B', 'RUNNERS ON BASE\n\n3B']
mask = clnDat[cols].applymap(lambda x: 1 if isinstance(x, str) else 0)

clnDat[cols] = mask[cols]

In [100]:
clnDat

ROAD\nSCORE  HOME\nSCORE  RUNNERS ON BASE\n\n1B  RUNNERS ON BASE\n\n2B  \
0              0            0                      0                      0   
1              0            0                      1                      0   
2              0            0                      1                      0   
3              0            0                      1                      0   
4              0            0                      1                      1   
..           ...          ...                    ...                    ...   
115            4            1                      1                      0   
116            4            1                      1                      0   
117            4            1                      0                      0   
118            4            1                      0                      0   
119            4            1                      1                      0   

     RUNNERS ON BASE\n\n3B  RUNS  OUTS                        PBP  
0                        0   0.0   0.0      IN                     
1                        0   0.0   1.0    S/S/IN                   
2                        0   0.0   1.0     S/IN                    
3                        0   0.0   0.0   B/B/S/IN                  
4                        0   0.0   1.0     S/IN                    
..                     ...   ...   ...                        ...  
115                      0   0.0   1.0    B/S/S/S                  
116                      0   0.0   1.0   S/S/B/B/S                 
117                      0   0.0   1.0   S/S/F/B/S                 
118                      0   0.0   0.0  F/B/B/B/S/B                
119                      0   0.0   0.0      IN                     

[120 rows x 8 columns]

In [186]:
switchs = []

for i, dat in enumerate(rawDat['INNING'].iloc[:-1]):
    
    if dat == rawDat['INNING'].values[i + 1]:
        
        switchs.append(0)
        
    else:
        
        switchs.append(1)
    
switchs.append(0)

In [207]:
#switchs

In [256]:
newdat = pd.DataFrame(columns = ['b1','b2','b3','balls','strikes','outs', 'runs', '3rdOut'])


j = 0
outs = 0
lastRuns = 0
for index, row in clnDat.iterrows():
    
    pitchSeq = pbpToBallStrikeArray(row['PBP'])
    
    switch = 0
    for pitch in pitchSeq:
        if switch == 0 :
            newdat.loc[j] = [row['RUNNERS ON BASE\n\n1B'], row['RUNNERS ON BASE\n\n2B'], row['RUNNERS ON BASE\n\n3B'],
                        pitch[0], pitch[1], outs, lastRuns, switchs[index]]
        else: 
            
            newdat.loc[j] = [row['RUNNERS ON BASE\n\n1B'], row['RUNNERS ON BASE\n\n2B'], row['RUNNERS ON BASE\n\n3B'],
                        pitch[0], pitch[1], outs, 0, switchs[index]]
        
        j += 1
        switch = 1
        
    lastRuns = row['RUNS']
    outs += row['OUTS']
    if outs >= 3:
        
        outs = 0

In [299]:
newdat = pd.DataFrame(columns = ['b1','b2','b3','balls','strikes','outs', 'runs', '3rdOut'])


j = 0
outs = 0
lastRuns = 0
for index, row in clnDat.iterrows():
    
    pitchSeq = pbpToBallStrikeArray(row['PBP'])
    
    switch = 0
    for pitch in pitchSeq:
        if switch == 0 :
            newdat.loc[j] = [row['RUNNERS ON BASE\n\n1B'], row['RUNNERS ON BASE\n\n2B'], row['RUNNERS ON BASE\n\n3B'],
                        pitch[0], pitch[1], outs, lastRuns, switchs[index]]
        else: 
            None
            #newdat.loc[j] = [row['RUNNERS ON BASE\n\n1B'], row['RUNNERS ON BASE\n\n2B'], row['RUNNERS ON BASE\n\n3B'],
            #            pitch[0], pitch[1], outs, 0, switchs[index]]
        
        j += 1
        switch = 1
        
    lastRuns = row['RUNS']
    outs += row['OUTS']
    if outs >= 3:
        
        outs = 0

In [300]:
## ways to load bases  = 6
## ways to have balls = 4
## ways to have strikes = 3
## ways to have outs = 3

6*4*3*3

216

In [301]:
simpleDat = newdat.drop(['strikes', 'balls'], axis = 'columns')

In [302]:
stateDict = dict()

stateDict[0] = [0, 0, 0, 0]
stateDict[1] = [1, 0, 0, 0]
stateDict[2] = [0, 1, 0, 0]
stateDict[3] = [0, 0, 1, 0]
stateDict[4] = [1, 1, 0, 0]
stateDict[5] = [1, 0, 1, 0]
stateDict[6] = [0, 1, 1, 0]
stateDict[7] = [1, 1, 1, 0]

stateDict[8]  = [0, 0, 0, 1]
stateDict[9]  = [1, 0, 0, 1]
stateDict[10] = [0, 1, 0, 1]
stateDict[11] = [0, 0, 1, 1]
stateDict[12] = [1, 1, 0, 1]
stateDict[13] = [1, 0, 1, 1]
stateDict[14] = [0, 1, 1, 1]
stateDict[15] = [1, 1, 1, 1]

stateDict[16] = [0, 0, 0, 2]
stateDict[17] = [1, 0, 0, 2]
stateDict[18] = [0, 1, 0, 2]
stateDict[19] = [0, 0, 1, 2]
stateDict[20] = [1, 1, 0, 2]
stateDict[21] = [1, 0, 1, 2]
stateDict[22] = [0, 1, 1, 2]
stateDict[23] = [1, 1, 1, 2]

In [303]:
8*3

24

In [304]:
stateSeries = []

for i, row in simpleDat.astype('uint8').iterrows():

    for j in range(23):
        isIn = 0 
        if stateDict[j] == list(row[:4]):
            
            #print(stateDict[j])
            #print(list(row[:4]))
            isIn = 1
            stateSeries.append(j)
            break
            
        if isIn == 0 and j == 23:
            
            print(row)
            
    if row['3rdOut'] == 1 and simpleDat['3rdOut'].astype('uint8').iloc[i + 1] == 0:
            stateSeries.append(24 + row['runs'])

IndexError: single positional indexer is out-of-bounds

In [284]:
np.unique(stateSeries)

array([ 0,  1,  4,  5,  7,  8,  9, 10, 12, 13, 14, 16, 17, 18, 19, 20, 21,
       22, 24, 26])

In [305]:
simpleDat.iloc[:50]

b1   b2   b3  outs  runs  3rdOut
0    0.0  0.0  0.0   0.0   0.0     0.0
1    1.0  0.0  0.0   0.0   0.0     0.0
4    1.0  0.0  0.0   1.0   0.0     0.0
6    1.0  0.0  0.0   2.0   0.0     0.0
10   1.0  1.0  0.0   2.0   0.0     1.0
12   0.0  0.0  0.0   0.0   0.0     0.0
16   0.0  0.0  0.0   1.0   0.0     0.0
20   0.0  0.0  0.0   2.0   0.0     1.0
25   0.0  0.0  0.0   0.0   0.0     0.0
31   0.0  0.0  0.0   1.0   0.0     0.0
32   0.0  0.0  0.0   2.0   0.0     1.0
35   0.0  0.0  0.0   0.0   0.0     0.0
36   1.0  0.0  0.0   0.0   0.0     0.0
38   0.0  0.0  0.0   2.0   0.0     0.0
42   1.0  0.0  0.0   2.0   0.0     1.0
44   0.0  0.0  0.0   0.0   0.0     0.0
46   1.0  0.0  0.0   0.0   0.0     0.0
53   1.0  1.0  0.0   0.0   0.0     0.0
54   1.0  1.0  1.0   0.0   0.0     0.0
56   1.0  1.0  0.0   1.0   1.0     0.0
60   1.0  1.0  0.0   2.0   0.0     1.0
62   0.0  0.0  0.0   0.0   0.0     0.0
67   0.0  0.0  0.0   1.0   0.0     0.0
73   0.0  0.0  0.0   2.0   0.0     0.0
76   0.0  1.0  0.0   2.0   0.0     1.0
78   0.0  0.0  0.0   0.0   0.0     0.0
80   0.0  0.0  0.0   1.0   0.0     0.0
83   0.0  0.0  0.0   2.0   0.0     1.0
87   0.0  0.0  0.0   0.0   0.0     0.0
90   0.0  0.0  0.0   1.0   0.0     0.0
94   0.0  0.0  0.0   2.0   0.0     0.0
97   0.0  1.0  0.0   2.0   0.0     0.0
99   1.0  0.0  0.0   2.0   1.0     0.0
103  1.0  0.0  1.0   2.0   0.0     0.0
109  1.0  1.0  1.0   2.0   0.0     1.0
112  0.0  0.0  0.0   0.0   0.0     0.0
118  1.0  0.0  0.0   0.0   0.0     0.0
119  1.0  0.0  1.0   0.0   0.0     0.0
123  1.0  0.0  1.0   1.0   0.0     1.0
128  0.0  0.0  0.0   0.0   0.0     0.0
134  0.0  0.0  0.0   1.0   0.0     0.0
139  1.0  0.0  0.0   1.0   0.0     0.0
143  1.0  1.0  0.0   1.0   0.0     0.0
144  1.0  0.0  1.0   2.0   0.0     1.0
148  0.0  0.0  0.0   0.0   0.0     0.0
153  0.0  0.0  0.0   1.0   0.0     0.0
159  0.0  0.0  0.0   2.0   0.0     1.0
162  0.0  0.0  0.0   0.0   0.0     0.0
165  0.0  0.0  0.0   1.0   0.0     0.0
169  0.0  0.0  0.0   2.0   0.0     0.0

In [286]:
## There are 23 + (4) = 27 states

In [287]:
## for a transition matrix the sum along a row should be 1 so that means that P_i,j (row, col) represents
## the probability of state going from state i -> j 

## Note that i am using transition vector super weirdly and wrongly, but its a good way to use it because
## I started calling it that in my head informally

def transitionVectorToCountMatrix(transitionVector):
    
    countMatrix = np.zeros(shape = (28, 28))
    
    for i, entryI in enumerate(transitionVector[:-1]):
        
        entryJ = transitionVector[i + 1]
        
        countMatrix[entryI][entryJ] += 1
        
    return countMatrix

In [288]:
countMat = transitionVectorToCountMatrix(stateSeries)

In [289]:
def countMatrixToTransitionMatrix( countMatrix ):
    
    transMat = deepcopy(countMatrix)
    
    for i, row in enumerate(transMat):
        
        sumRow = np.sum(row)
        
        if sumRow != 0:
            transMat[i] *= 1./sumRow
        
    return transMat

In [290]:
transMat = countMatrixToTransitionMatrix(countMat)

In [296]:
transMat[0]

array([0.75438596, 0.07017544, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.1754386 , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        ])

In [292]:
transMat[24]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [293]:
stateSeries

[0,
 1,
 1,
 1,
 9,
 9,
 17,
 17,
 17,
 17,
 20,
 20,
 24,
 0,
 0,
 0,
 0,
 8,
 8,
 8,
 8,
 16,
 16,
 16,
 16,
 16,
 24,
 0,
 0,
 0,
 0,
 0,
 0,
 8,
 16,
 16,
 16,
 24,
 0,
 1,
 1,
 16,
 16,
 16,
 16,
 17,
 17,
 24,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 4,
 7,
 7,
 12,
 12,
 12,
 12,
 20,
 20,
 24,
 0,
 0,
 0,
 0,
 0,
 8,
 8,
 8,
 8,
 8,
 8,
 16,
 16,
 16,
 18,
 18,
 24,
 0,
 0,
 8,
 8,
 8,
 16,
 16,
 16,
 16,
 24,
 0,
 0,
 0,
 8,
 8,
 8,
 8,
 16,
 16,
 16,
 18,
 18,
 17,
 17,
 17,
 17,
 21,
 21,
 21,
 21,
 21,
 21,
 24,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 5,
 5,
 5,
 5,
 13,
 13,
 13,
 13,
 13,
 24,
 0,
 0,
 0,
 0,
 0,
 0,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 12,
 21,
 21,
 21,
 21,
 24,
 0,
 0,
 0,
 0,
 0,
 8,
 8,
 8,
 8,
 8,
 8,
 16,
 16,
 16,
 24,
 0,
 0,
 0,
 8,
 8,
 8,
 8,
 16,
 16,
 17,
 24,
 0,
 0,
 0,
 0,
 0,
 0,
 8,
 16,
 24,
 0,
 8,
 8,
 8,
 8,
 9,
 9,
 14,
 14,
 13,
 22,
 22,
 18,
 18,
 18,
 18,
 18,
 18,
 18,
 20,
 20,
 20,
 20,
 20,
 20,
 24,
 0,
 0,
 0,
 0,
 8,
 8,
 8,
 8,
 16,


In [294]:
np.save('transitionMatrix.npy', transMat)

In [295]:
transMat.shape

(28, 28)